# Generated by Django 3.2.2 on 2021-05-09 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publishers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField(default=0)),
                ('month', models.CharField(max_length=50)),
                ('hours', models.IntegerField(default=0)),
                ('placements', models.IntegerField(default=0)),
                ('videos', models.IntegerField(default=0)),
                ('return_visit', models.IntegerField(default=0)),
                ('bible_study', models.IntegerField(default=0)),
                ('remarks', models.TextField(max_length=200)),
                ('publisher', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='publishers.publishers')),
            ],
        ),
    ]
