# Generated by Django 3.2.2 on 2021-05-09 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_report_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='remarks',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
