# Generated by Django 3.2.2 on 2021-05-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_report_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='auxiPr',
            field=models.BooleanField(default=False),
        ),
    ]
