# Generated by Django 3.2.2 on 2021-06-04 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0008_auto_20210530_0205'),
        ('report', '0005_report_auxipr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publishers.publishers'),
        ),
    ]
