# Generated by Django 3.2.2 on 2021-08-28 01:04

from django.db import migrations, models
import django.db.models.deletion
import report.models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0010_alter_publishers_privilage'),
        ('report', '0006_alter_report_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pending',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.CreateModel(
            name='Pioneer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auxi_pioneer', models.BooleanField(default=False, null=True)),
                ('month', models.CharField(max_length=50)),
                ('year', models.IntegerField(default=report.models.get_current_year)),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publishers.publishers')),
            ],
        ),
    ]
