# Generated by Django 3.2.2 on 2021-08-31 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20210828_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pioneer',
            name='auxi_pioneer',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
