# Generated by Django 3.2.2 on 2021-09-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_remove_report_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
