# Generated by Django 3.2.2 on 2021-05-14 13:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by', models.CharField(max_length=100)),
                ('meeting_date', models.DateField(default=datetime.datetime(2021, 5, 14, 13, 41, 2, 560536, tzinfo=utc))),
                ('image', models.ImageField(upload_to='post_images')),
            ],
        ),
    ]
