# Generated by Django 3.2.2 on 2021-05-14 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='meeting_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
