# Generated by Django 3.2.2 on 2021-05-14 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0002_auto_20210509_1025'),
        ('bulletin', '0002_alter_bulletin_meeting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='uploaded_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='publishers.publishers'),
        ),
    ]
