# Generated by Django 3.2.2 on 2021-05-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishers',
            name='contact',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='publishers',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
