# Generated by Django 3.2.2 on 2021-05-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0002_auto_20210509_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishers',
            name='privilage',
            field=models.CharField(choices=[('pub', 'Publisher'), ('aux', 'Auxillary Pioneer'), ('rp', 'Regular Pioneer'), ('elder', 'Elder')], default='pub', max_length=50),
        ),
    ]
