# Generated by Django 3.2.2 on 2021-05-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0003_publishers_privilage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishers',
            name='privilage',
            field=models.CharField(choices=[('Publisher', 'Publisher'), ('Auxillary Pioneer', 'Auxillary Pioneer'), ('Regular Pioneer', 'Regular Pioneer'), ('Elder', 'Elder')], default='pub', max_length=50),
        ),
    ]
