# Generated by Django 3.2.2 on 2021-05-19 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0005_alter_publishers_privilage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishers',
            name='privilage',
        ),
    ]
