# Generated by Django 3.2.2 on 2021-05-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0007_publishers_privilage'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishers',
            name='elder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publishers',
            name='privilage',
            field=models.CharField(choices=[('Publisher', 'Publisher'), ('Auxillary Pioneer', 'Auxillary Pioneer'), ('Regular Pioneer', 'Regular Pioneer')], default='Publisher', max_length=50),
        ),
    ]
