# Generated by Django 3.2.2 on 2021-08-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0008_auto_20210530_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishers',
            name='baptismal_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='publishers',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='publishers',
            name='privilage',
            field=models.CharField(choices=[('Publisher', 'Publisher'), ('Unbaptized Publisher', 'Unbaptized Publisher'), ('Auxillary Pioneer', 'Auxillary Pioneer'), ('Regular Pioneer', 'Regular Pioneer')], default='Publisher', max_length=50),
        ),
    ]
