# Generated by Django 3.2.2 on 2021-08-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0009_auto_20210823_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishers',
            name='privilage',
            field=models.CharField(choices=[('Publisher', 'Publisher'), ('Irregular', 'Irregular'), ('Inactive', 'Inactive'), ('Unbaptized Publisher', 'Unbaptized Publisher'), ('Auxillary Pioneer', 'Auxillary Pioneer'), ('Regular Pioneer', 'Regular Pioneer')], default='Publisher', max_length=50),
        ),
    ]
