# Generated by Django 3.2.2 on 2021-08-31 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0010_alter_publishers_privilage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('group', models.IntegerField(default=0)),
                ('birthday', models.DateField(null=True)),
                ('baptismal_date', models.DateField(null=True)),
                ('contact', models.CharField(blank=True, max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_leaved', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='publishers',
            name='inactive',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='publishers',
            name='irregular',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
