# Generated by Django 3.2.2 on 2021-08-31 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0011_auto_20210831_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishers',
            name='privilage',
            field=models.CharField(choices=[('Publisher', 'Publisher'), ('Unbaptized Publisher', 'Unbaptized Publisher'), ('Auxillary Pioneer', 'Auxillary Pioneer'), ('Regular Pioneer', 'Regular Pioneer')], default='Publisher', max_length=50),
        ),
    ]
