# Generated by Django 3.2.2 on 2021-08-31 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0012_alter_publishers_privilage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishers',
            name='baptismal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publishers',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
